//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.17 at 01:00:20 PM CET 
//


package be.kroma.soapmessages;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.kroma.soapmessages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.kroma.soapmessages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AutocompleteRequest }
     * 
     */
    public AutocompleteRequest createAutocompleteRequest() {
        return new AutocompleteRequest();
    }

    /**
     * Create an instance of {@link AutocompleteResponse }
     * 
     */
    public AutocompleteResponse createAutocompleteResponse() {
        return new AutocompleteResponse();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link SuggestRequest }
     * 
     */
    public SuggestRequest createSuggestRequest() {
        return new SuggestRequest();
    }

    /**
     * Create an instance of {@link SuggestResponse }
     * 
     */
    public SuggestResponse createSuggestResponse() {
        return new SuggestResponse();
    }

    /**
     * Create an instance of {@link SuggestResults }
     * 
     */
    public SuggestResults createSuggestResults() {
        return new SuggestResults();
    }

    /**
     * Create an instance of {@link RangeRequest }
     * 
     */
    public RangeRequest createRangeRequest() {
        return new RangeRequest();
    }

    /**
     * Create an instance of {@link RangeResponse }
     * 
     */
    public RangeResponse createRangeResponse() {
        return new RangeResponse();
    }

    /**
     * Create an instance of {@link RangeResults }
     * 
     */
    public RangeResults createRangeResults() {
        return new RangeResults();
    }

    /**
     * Create an instance of {@link ReverseRequest }
     * 
     */
    public ReverseRequest createReverseRequest() {
        return new ReverseRequest();
    }

    /**
     * Create an instance of {@link ReverseResponse }
     * 
     */
    public ReverseResponse createReverseResponse() {
        return new ReverseResponse();
    }

    /**
     * Create an instance of {@link ReverseResults }
     * 
     */
    public ReverseResults createReverseResults() {
        return new ReverseResults();
    }

    /**
     * Create an instance of {@link FeedbackRequest }
     * 
     */
    public FeedbackRequest createFeedbackRequest() {
        return new FeedbackRequest();
    }

    /**
     * Create an instance of {@link FeedbackResponse }
     * 
     */
    public FeedbackResponse createFeedbackResponse() {
        return new FeedbackResponse();
    }

    /**
     * Create an instance of {@link FeedbackResults }
     * 
     */
    public FeedbackResults createFeedbackResults() {
        return new FeedbackResults();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link SuggestResult }
     * 
     */
    public SuggestResult createSuggestResult() {
        return new SuggestResult();
    }

    /**
     * Create an instance of {@link SuggestStreetResult }
     * 
     */
    public SuggestStreetResult createSuggestStreetResult() {
        return new SuggestStreetResult();
    }

    /**
     * Create an instance of {@link RangeResult }
     * 
     */
    public RangeResult createRangeResult() {
        return new RangeResult();
    }

    /**
     * Create an instance of {@link FeedbackResult }
     * 
     */
    public FeedbackResult createFeedbackResult() {
        return new FeedbackResult();
    }

}
