//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.17 at 01:00:20 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://api.pro6pp.nl/v1/soap/api.wsdl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.kroma.soapmessages;
